pythonweb/music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'
urlpatterns = [
    #/music/
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    #/music/idofalbum/
    url(r'^(?P<pk>[0-9+]+)/$', views.DetailView.as_view(), name='detail'),

     #/music/album/add-album
    url(r'album/add/$', views.AlbumCreate.as_view(), name='add-album'),

    #/music/album/2/ 
    url(r'album/(?P<pk>[0-9+]+)/$', views.AlbumUpdate.as_view(), name='update-album'),

    #/music/album/2/ 
    url(r'album/(?P<pk>[0-9+]+)/delete/$', views.AlbumDelete.as_view(), name='delete-album'),

]

pythonweb/pythonweb/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pythonweb/music/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Album(models.Model):
    artist = models.CharField(max_length=50)
    album_title = models.CharField(max_length=100)
    genre = models.CharField(max_length=10)
    album_logo = models.FileField()
     
    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + ' - ' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_fav = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

pythonweb/music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

pythonweb/music/views.py
# from django.http import Http404
# from django.shortcuts import render
# from django.http import HttpResponse
# from django.template import loader
# from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm
from .models import Album


# def index(request):
#     all_albums = Album.objects.all()
#     template = loader.get_template('music/index.html')
#     context = {
#         'all_albums': all_albums,
#     }
#     # html = ''
#     # for album in all_albums:
#     #     url = '/music/' + str(album.id) + '/'
#     #     html +='<a href="' + url +'">' + album.album_title + '</a><br>'
#     #return HttpResponse(template.render(context, request))
#     return render(request, 'music/index.html', context)

# def detail(request, album_id):
#     # try:
#     #     album = Album.objects.get(id=album_id)
#     # except Album.DoesNotExist:
#     #     raise Http404("Album does not exist")
#     album = get_object_or_404(Album, pk=album_id)
#     return render(request, 'music/detail.html', {'album': album})
#     #return HttpResponse("<h2> Details for Album id: " + str(album_id) + "</h2>")


# def favorite(request, album_id):
#     album = get_object_or_404(Album, pk=album_id)
#     try:
#         selected_song = album.song_set.get(pk=request.POST['song'])
#     except (KeyError, Song.DoesNotExist):
#         return render(request, 'music/detail.html', {
#         'album':album,
#          'error_message': "You didn't Selected Any song"
#         })
#     else:
#         selected_song.is_fav = True
#         selected_song.save()
#         return render(request, 'music/detail.html', {'album': album})
class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'


    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

    
class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration.html'


    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)


        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username,password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('music:index')
            
        return render(request, self.template_name, {'form': form})

pythonweb/music/templates/music/album_form.html
{% extends 'music/base.html' %} {% block body %}

<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" method="post" enctype="multipart/form-data">
                        {% csrf_token %} {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-large btn-block btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}

pythonweb/music/templates/music/base.html
<html>

<body>
    <!-- Css files !-->
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#Menu_collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
                <a class="navbar-brand" href="{% url 'music:index' %}">Music</a>
            </div>

            <div class="collapse navbar-collapse" id="Menu_collapse">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="#">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"> Albums<span class="sr-only">(current)</span></span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="glyphicon glyphicon-music" aria-hidden="true"> Songs </span></a>
                    </li>
                    <!-- <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li> -->
                </ul>
                <form class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Login</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href=""> <span class="glyphicon glyphicon-off" aria-hidden="true"> Logout </span></a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'music:add-album' %}"><span class="glyphicon glyphicon-Plus" aria-hidden="true"> Add Album </span></a></li>
                </ul>

            </div>
        </div>
    </nav>
    {% block body %} {% endblock %}
</body>

</html>

pythonweb/music/templates/music/detail.html
{% extends 'music/base.html' %} {% block body %}
<img src="{{ album.album_logo.url }}" alt="" style="width:250px">
<h1> {{ album.album_title }} </h1>
<h2>{{ album.artist }}</h2>

{% for song in album.song_set.all %} {{ song.song_title }} {% if song.is_fav %}
<img src="https://media.giphy.com/media/crf9zhpH2N3Nu/giphy.gif" alt="" style="width:16px"> {% endif %}
<br>
<br> {% endfor %} {% endblock %}

pythonweb/music/templates/music/details.html
{% extends 'music/base.html' %} {% block body %}
<img src="{{album.album_logo}}" alt="album_logo">
<h1>{{ album.album_title }}</h1>
<h3>{{ album.artist }}</h3>
<!-- <ul>
    {% for song in album.song_set.all %}
    <li>{{song.song_title}} - {{ song.file_type}}</li>
    {% endfor %}
</ul> -->
<!-- {% if error_message %}
<p>
    <strong>
                {{ error_message }}
            </strong>
</p>

{% endif %} -->

<!-- <form action="{% url 'music:favorite' album.id %}" method="post"> -->
<!-- {% csrf_token %} -->
{% for song in album.song_set.all %}
<!-- <input type="radio" name="song" id="song{{ forloop.counter}}}" value="{{song.id}}">
<label for="song{{ forloop.counter}}}"> -->
{{ song.song_title }} {% if song.is_fav %}
<img src="https://media.giphy.com/media/crf9zhpH2N3Nu/giphy.gif" alt=""> {% endif %}
</label><br> {% endfor %}
<!-- <button type="submit">favorite</button>
</form> -->

{% endblock %}

pythonweb/music/templates/music/form-template.html
{% for field in form %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">
        {{field.errors}}
        </span>
    </div>
    <label class="contorl-label col-sm-2"> {{ field.label_tag }}</label>
    <div class="col-sm-10">
        {{field}}
    </div>
</div>
{% endfor %}

pythonweb/music/templates/music/index.html
{% extends 'music/base.html' %}{% block body %}
<!-- {% if all_albums %} -->
<div class="conatiner">
    <marquee behavior="" direction="" class="musix" style="">Welcome to Music Listening</marquee>
</div>
<ul>
    {{ object_list }} {% for album in all_albums %}
    <li style="color:gold">
        <!-- /music/{{ album.id }}/!-->
        <a href="{% url 'music:detail' album.id %}" style="color:darkturquoise">{{ album.album_title}}</a>
    </li>
    <form action="{% url 'music:delete-album' album.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="album_id" value="{{ album.id }}">
        <button type="submit" class="btn btn-default btn-sm btn-favorite">
            <span class="glyphicon glyphicon-trash"> 
            </span>
        </button>
    </form>
    {% endfor %}
</ul>
<!-- {% else %}
<h2 style="display:inline">No Albums Found</h2>
{% endif %}  -->
{% endblock %}

pythonweb/music/templates/music/registration.html
{% extends 'music/base.html' %} {% block body %}

<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" method="post" enctype="multipart/form-data">
                        {% csrf_token %} {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-large btn-block btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}